# Generated by Django 4.0.2 on 2022-03-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product images', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterModelOptions(
            name='productreviews',
            options={'verbose_name': 'Product reviews', 'verbose_name_plural': 'Product reviews'},
        ),
        migrations.AlterModelOptions(
            name='productversion',
            options={'verbose_name': 'Product version', 'verbose_name_plural': 'Product versions'},
        ),
        migrations.AlterModelOptions(
            name='propertyname',
            options={'verbose_name': 'Property name', 'verbose_name_plural': 'Propert names'},
        ),
        migrations.AlterModelOptions(
            name='propertyvalues',
            options={'verbose_name': 'Property values', 'verbose_name_plural': 'Property values'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysweetchild', to='product.category'),
        ),
    ]
