# Generated by Django 4.0.2 on 2022-04-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AddField(
            model_name='productimages',
            name='image_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Image title'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='main pic'),
        ),
    ]
