# Generated by Django 4.0.2 on 2022-03-11 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPropertyValues',
        ),
        migrations.AddField(
            model_name='brand',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='product.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_sub_cat', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='product.category'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='product_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.productversion'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='product_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='production_version_product_review', to='product.productversion'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_product_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_product_version', to='product.product'),
        ),
        migrations.AddField(
            model_name='productversion',
            name='publications',
            field=models.ManyToManyField(to='product.PropertyValues'),
        ),
        migrations.AddField(
            model_name='propertyname',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_property_name', to='product.category'),
        ),
        migrations.AddField(
            model_name='propertyvalues',
            name='property_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_name_property_value', to='product.propertyname'),
        ),
    ]
