# Generated by Django 4.0.2 on 2022-06-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='same_color_product_versions', to='product.color'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='same_size_product_versions', to='product.size'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
