# Generated by Django 4.0.2 on 2022-03-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
