# Generated by Django 4.0.2 on 2022-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
