# Generated by Django 4.0.2 on 2022-06-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_title_az_category_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='is_main',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
