# Generated by Django 4.0.2 on 2022-04-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productversion_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productversion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='is_main',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_product_version', to='product.product'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
