# Generated by Django 4.0.2 on 2022-04-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productversion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
