# Generated by Django 4.0.2 on 2022-06-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_color_hex_code_alter_productreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
    ]
