# Generated by Django 4.0.2 on 2022-04-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productversion_old_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productversion',
            old_name='price',
            new_name='new_price',
        ),
    ]
