# Generated by Django 4.0.2 on 2022-07-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productreview_created_at_productreview_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product_version',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='product.productversion'),
        ),
    ]
