# Generated by Django 4.0.2 on 2022-03-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'verbose_name': 'Blog comment', 'verbose_name_plural': 'Blog comments'},
        ),
        migrations.AlterModelOptions(
            name='blogreviews',
            options={'verbose_name': 'Blog reviews', 'verbose_name_plural': 'Blog reviews'},
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(default=1, max_length=40),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='parent_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_sub_cat', to='blog.blogcategory'),
        ),
    ]
