# Generated by Django 4.0.2 on 2022-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
