# Generated by Django 4.0.2 on 2022-03-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_blogcomment_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
    ]
