# Generated by Django 4.0.2 on 2022-07-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('percentage', models.CharField(blank=True, max_length=20, null=True, verbose_name='Percentage')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='productversion',
            name='color',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='same_color_product_versions', to='product.color'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Discounted Price'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productversion',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='product.discount'),
        ),
    ]
