# Generated by Django 4.0.2 on 2022-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productversion',
            name='hide',
            field=models.BooleanField(default=False, help_text='Məhsulun səhifədə görünməsini dayandırmaq', verbose_name='Hide'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Daxil etdiyiniz şəkillərdən yalnız birini məhsulun əsas şəkli olaraq seçin', verbose_name='Main picture'),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='\n        Buraya hər hansı məbləğ qeyd etməyə ehtiyac yoxdur. Daxil etdiyiniz qiymət və endirim (əgər varsa) nəzərə alınaraq avtomatik hesablanma aparılır.', max_digits=6, null=True, verbose_name='Discounted Price'),
        ),
    ]
