# Generated by Django 4.0.2 on 2022-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productversion_hide_alter_productimage_is_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='confirm',
            field=models.BooleanField(default=False, help_text='Confirm review', verbose_name='Confirm'),
        ),
    ]
