# Generated by Django 4.0.2 on 2022-07-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='Product_wishlist', to='product.ProductVersion'),
        ),
    ]
