# Generated by Django 4.0.2 on 2022-03-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
