# Generated by Django 4.0.2 on 2022-03-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
    ]
